### ISSUE TITLE
Resource versions not updated after pausing the latest version

### ISSUE THREAD

**Issue by weymanf** [concourse/s3-resource#68] opened 2017-02-23 20:03 UTC
We butchered a version in a s3 bucket so basically our version would not update the older versions because we believe it just compares the name of the newest one and sees if it needs to get a later one.
For example
```
2.0.0-dev.1.tgz
1.3.0-dev.40.tgz
1.3.0-dev.39.tgz
1.3.0-dev.38.tgz
```

We accidentally put a 2.0.0 version into our bucket. And we are still building 1.3.0-dev versions. However, concourse will not update anymore 1.3.0 versions (e.g, 1.3.0-dev-41) because we believe 2.0.0 sits on top because it's a higher number. 

We would like a way to clear the resource cache and reset through fly at least. Or have the s3 resource properly check the version and the timestamp and put the latest one inserted as the latest one we want to use.

**Comment by chendrix** [comment] 2017-05-23 23:11
Closing as dupe of concourse/concourse#1038

**Closed by chendrix** 2017-05-23 23:11 UTC
